### ISSUE TITLE
Error in rosinstall: No 'ros' stack detected. 

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/ROSEndEffectorPackageManager#2]
Maybe interesting to check:

http://wiki.ros.org/rosinstall/Troubleshooting

**Comment by liesrock** [comment]
As highlight in https://github.com/ADVRHumanoids/ROSEndEffectorPackageManager/issues/1#issuecomment-625138429

should be just a warning, but we can double check.

**Comment by torydebra** [comment]
I found by chance another command:
~~~
rosco -r .rosinstall
~~~
Explained [here](https://docs.ros.org/independent/api/rosinstall/html/rosco.html)

This one is better for us because it only clones repos that for now is what we need. So the error is not present anymore.

I am not sure if this command will also "pull" further commits, I have to check

**Comment by liesrock** [comment]
Nice! i will check too, because the pull feature to update the code is vital!

**Comment by torydebra** [comment]
rosco does not "pull" (while rosinstall yes), it returns an error if the directory is not empty

**Comment by torydebra** [comment]
As they say... [RTFM](https://en.wikipedia.org/wiki/RTFM)

I found `rows update` [here](https://docs.ros.org/independent/api/rosinstall/html/rosws.html) that is exactly what we want: clone at the beginning and pull the updates for the future.

**Comment by torydebra** [comment]
@liesrock on my sistem the new command works: I can "clone" all from scratch but also use it to "pull all"

If it is fine also for you, I will substitute `rosintall .` with `rosws update`

**Comment by liesrock** [comment]
Nice! Tested and working also for me: looks a nice tool, if you can update the documentation (readthedocs) we can close this!

**Comment by torydebra** [comment]
> @liesrock on my sistem the new command works: I can "clone" all from scratch but also use it to "pull all"
> 
> If it is fine also for you, I will substitute `rosintall .` with `rosws update`

Done in the [last commit](https://github.com/ADVRHumanoids/ROSEndEffectorDocs/commit/013c59253f4d54a9f9ff28e58dd3c2b93136297a). 

With rowsw instead of rosintall, the error indicated in this issue is not a thing anymore, so I close
